### ISSUE TITLE
Account in use?

### ISSUE THREAD

**Issue by evanfrawley** [noni/SMS-Rest#1]
Hello,
Is this account still in use? I’m working on a project with “noni” as the name. I would love to have this username! Are you willing to part with this account?

**Comment by noni** [comment]
Hi,
The account is not anymore active.

Thanks!
    On ‎Sunday‎, ‎9‎ ‎September‎ ‎2018‎ ‎01‎:‎34‎:‎28‎ ‎PM‎ ‎PDT, Evan Frawley <notifications@github.com> wrote:  
 
 
Hello,
Is this account still in use? I’m working on a project with “noni” as the name. Are you willing to part with this account?

**Comment by evanfrawley** [comment]
Hi! Thanks for replying :) if this account isn’t active anymore, would you be willing to give or sell it to me? Feel free to reply to evanfrawley(at)gmail.com if you’d like to talk specifics! Thank you!
